<?php

use Bojka\Roster\Objects\Profile;
use Bojka\Roster\Supports\ImageSupport;
use function Bokja\Roster\prefixed;

if (!defined('ABSPATH')) {
    exit;
}

return [
    'post' => [
        prefixed('baptismal_name')            => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '세레명',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('birthday')                  => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '생일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('current_assignment')        => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '현소임지',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('date_of_death')             => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '사망일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('entrance_date')             => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '입회일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('initial_profession_date')   => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '초(初)서원일, 첫 서원일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('monastic_name')             => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '수도명',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('name_day')                  => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '축일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => [Profile::class, 'sanitizeNameDay'],
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('nationality')               => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '국적',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('ordination_date')           => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '서품일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('perpetual_profession_date') => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'string',
            'description'       => '종신서원일',
            'single'            => true,
            'default'           => '',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
        prefixed('profile_image')             => [
            'object_subtype'    => ROSTER_CPT_PROFILE,
            'type'              => 'array',
            'description'       => '사진',
            'single'            => true,
            'default'           => [],
            'sanitize_callback' => [ImageSupport::class, 'sanitize'],
            'auth_callback'     => null,
            'show_in_rest'      => false,
            'revisions_enabled' => false,
            'get_filter'        => null,
        ],
    ],
];
